version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    env_file:
      - config.env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - config.env

volumes:
  pgdata:
